"use client";

import "./globals.css";
import { useState } from "react";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { ColorModeContext, useMode } from "@/theme";

import Topbar from "@/views/global/Topbar";
import Sidebar from "@/views/global/Sidebar";

// export const metadata = {
//   title: "Dashboard",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [theme, colorMode] = useMode();
  const [isSidebar, setIsSidebar] = useState(true);

  return (
    <html lang="en">
      <body>
        <ColorModeContext.Provider value={colorMode}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <div className="app">
              {/* Sidebar global */}

              <Sidebar isSidebar={isSidebar} />
              <main className="content">
                {/* Topbar global */}
                <Topbar setIsSidebar={setIsSidebar} />

                {children}
              </main>
            </div>
          </ThemeProvider>
        </ColorModeContext.Provider>
      </body>
    </html>
  );
}
